// In-browser PyNite solver: Pyodide (Python on WebAssembly) running in a Web Worker.
// The worker and its Python files live in public/pynite and are generated by
// paramele-solvers/scripts/build_browser_bundle.sh.

let worker = null;
let next_id = 0;
let initialized = false;
const pending = new Map();

function getWorker() {
  if (!worker) {
    worker = new Worker(`${process.env.PUBLIC_URL}/pynite/pynite.worker.js`, { type: "module" });
    worker.onmessage = (event) => {
      const { id, ok, error, ...data } = event.data;
      const request = pending.get(id);
      if (!request) return;
      pending.delete(id);
      if (ok) request.resolve(data);
      else request.reject(new Error(error));
    };
    worker.onerror = (event) => {
      pending.forEach((request) => request.reject(new Error(event.message || "PyNite worker failed")));
      pending.clear();
      worker = null;
      initialized = false;
    };
  }
  return worker;
}

function request(message) {
  const id = next_id++;
  return new Promise((resolve, reject) => {
    pending.set(id, { resolve, reject });
    getWorker().postMessage({ id, ...message });
  });
}

/** Starts downloading Pyodide and PyNite in the background, so the first solve is faster. */
const preload = () => request({ type: "init" }).then((data) => {
  initialized = true;
  return data;
});

/** Whether the Python runtime is already loaded (a solve won't need to download it). */
const isReady = () => initialized;

/**
 * @param {Object} model structural model, already repaired for "pynite"
 * @returns {Promise<{results: Object, timings: {init_ms: number, solve_ms: number, sparse: boolean}}>}
 */
const solve = (model) => request({ type: "solve", model }).then((data) => {
  initialized = true;
  return data;
});

const pyniteWasm = { preload, isReady, solve };
export default pyniteWasm;
